### ISSUE TITLE
Inventory breaks after doing the hack.

### ISSUE THREAD

**Issue by HeroicVault** [avilchiis/av_union#1]
every time i do the hack it wont let me open my inventory after doing the hack.
SCRIPT ERROR: @qb-inventory/server/main.lua:2363: attempt to index a nil value (field '?')

**Comment by avilchiis** [comment]
That line doesn't have anything to do with my script (?) is about the [/giveitem command](https://github.com/qbcore-framework/qb-inventory/blob/09975a7a96222b285f99666d378850368adf70bd/server/main.lua#L2363C7-L2363C15) Make sure you are using the latest version of qb-inventory.
