### ISSUE TITLE
ps-inventory

### ISSUE THREAD

**Issue by TwistedNF** [avilchiis/av_union#3]
This seenms to not be compatible with ps-inventory. It throws an error when trying to do the vault hack which will be listed below.

script:av_union] SCRIPT ERROR: @av_union/server/framework/functions.lua:27: No such export HasItem in resource qb-inventory

![2hxfOGx](https://github.com/avilchiis/av_union/assets/53712713/af3066a3-294d-4226-88fc-9a9d579cd532)

**Comment by avilchiis** [comment]
You are using Config.Inventory = "qb-inventory" when your inventory is named ps-inventory ofc you are gonna get an export error.

**Comment by TwistedNF** [comment]
I have it set to ps-inventory and that still doesn't do jack shit lol. It says "Union Heist. You don't have the needed item" and i have the hack_vault, c4 and thermite

**Comment by TwistedNF** [comment]
> You are using Config.Inventory = "qb-inventory" when your inventory is named ps-inventory ofc you are gonna get an export error.

So I found the issue. It's in the qb-core\shared\items.lua I'll post the picture below to explain better. You see how the hack vault goes ['hack_vault'] = { ['name'] = 'hacking_phone', |  Well it causes the inventory to crash. If the name matches like this ['hack_vault'] = { ['name'] = 'hack_vault, It doesn't crash and everything works fine. If you need a video I can make one or maybe get in a discord call with you?

![WkKBSsm](https://github.com/avilchiis/av_union/assets/53712713/f35958e5-90bc-444d-8e0c-a1c3b844ea75)

**Comment by avilchiis** [comment]
A video for what exactly? The problem is how YOU registered the item in your qb-core this is not even related to my script lol.
